#!/bin/bash

var=$(hidutil property --get UserKeyMapping | wc -l)

if [[ $var -le 2 ]]; then
	hidutil property --set '{"UserKeyMapping":
    [
     {"HIDKeyboardModifierMappingSrc":0x700000039,
      "HIDKeyboardModifierMappingDst":0x70000002A},
      {"HIDKeyboardModifierMappingSrc":0x700000065,
      "HIDKeyboardModifierMappingDst":0x7000000E3}
    ]
}' > /dev/null
else
	hidutil property --set '{"UserKeyMapping":[]}' > /dev/null
fi
